[mysql]
  dbname     = "earthquake-alert"
  host       = "127.0.0.1"
  port       = 3306
  user       = "docker"
  pass       = "docker"
  sslmode    = "false"
  whitelist = [
    "JmaXmlEntries",
    "TwitterThreads",
    "Earthquakes",
    "TsunamiConnects",
    "TsunamiInfos",
    "EarthquakeInfos",
    "EarthquakeEpicenters",
    "EarthquakeReports",
    "EarthquakeActivity",
    "EarthquakeUpdate",
    "EarthquakeCount",
  ]
