// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AreaCodes             string
	EarthquakeActivity    string
	EarthquakeCount       string
	EarthquakeEpicenters  string
	EarthquakeInfos       string
	EarthquakeReports     string
	EarthquakeUpdate      string
	Earthquakes           string
	IntensityStationCodes string
	JmaXmlEntries         string
	PrefectureCodes       string
	TsunamiConnects       string
	TsunamiInfos          string
	TwitterThreads        string
}{
	AreaCodes:             "AreaCodes",
	EarthquakeActivity:    "EarthquakeActivity",
	EarthquakeCount:       "EarthquakeCount",
	EarthquakeEpicenters:  "EarthquakeEpicenters",
	EarthquakeInfos:       "EarthquakeInfos",
	EarthquakeReports:     "EarthquakeReports",
	EarthquakeUpdate:      "EarthquakeUpdate",
	Earthquakes:           "Earthquakes",
	IntensityStationCodes: "IntensityStationCodes",
	JmaXmlEntries:         "JmaXmlEntries",
	PrefectureCodes:       "PrefectureCodes",
	TsunamiConnects:       "TsunamiConnects",
	TsunamiInfos:          "TsunamiInfos",
	TwitterThreads:        "TwitterThreads",
}
