// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testEarthquakeCounts(t *testing.T) {
	t.Parallel()

	query := EarthquakeCounts()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testEarthquakeCountsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeCount{}
	if err = randomize.Struct(seed, o, earthquakeCountDBTypes, true, earthquakeCountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeCount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := EarthquakeCounts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testEarthquakeCountsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeCount{}
	if err = randomize.Struct(seed, o, earthquakeCountDBTypes, true, earthquakeCountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeCount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := EarthquakeCounts().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := EarthquakeCounts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testEarthquakeCountsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeCount{}
	if err = randomize.Struct(seed, o, earthquakeCountDBTypes, true, earthquakeCountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeCount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := EarthquakeCountSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := EarthquakeCounts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testEarthquakeCountsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeCount{}
	if err = randomize.Struct(seed, o, earthquakeCountDBTypes, true, earthquakeCountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeCount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := EarthquakeCountExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if EarthquakeCount exists: %s", err)
	}
	if !e {
		t.Errorf("Expected EarthquakeCountExists to return true, but got false.")
	}
}

func testEarthquakeCountsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeCount{}
	if err = randomize.Struct(seed, o, earthquakeCountDBTypes, true, earthquakeCountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeCount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	earthquakeCountFound, err := FindEarthquakeCount(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if earthquakeCountFound == nil {
		t.Error("want a record, got nil")
	}
}

func testEarthquakeCountsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeCount{}
	if err = randomize.Struct(seed, o, earthquakeCountDBTypes, true, earthquakeCountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeCount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = EarthquakeCounts().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testEarthquakeCountsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeCount{}
	if err = randomize.Struct(seed, o, earthquakeCountDBTypes, true, earthquakeCountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeCount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := EarthquakeCounts().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testEarthquakeCountsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	earthquakeCountOne := &EarthquakeCount{}
	earthquakeCountTwo := &EarthquakeCount{}
	if err = randomize.Struct(seed, earthquakeCountOne, earthquakeCountDBTypes, false, earthquakeCountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeCount struct: %s", err)
	}
	if err = randomize.Struct(seed, earthquakeCountTwo, earthquakeCountDBTypes, false, earthquakeCountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeCount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = earthquakeCountOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = earthquakeCountTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := EarthquakeCounts().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testEarthquakeCountsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	earthquakeCountOne := &EarthquakeCount{}
	earthquakeCountTwo := &EarthquakeCount{}
	if err = randomize.Struct(seed, earthquakeCountOne, earthquakeCountDBTypes, false, earthquakeCountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeCount struct: %s", err)
	}
	if err = randomize.Struct(seed, earthquakeCountTwo, earthquakeCountDBTypes, false, earthquakeCountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeCount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = earthquakeCountOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = earthquakeCountTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := EarthquakeCounts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func earthquakeCountBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *EarthquakeCount) error {
	*o = EarthquakeCount{}
	return nil
}

func earthquakeCountAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *EarthquakeCount) error {
	*o = EarthquakeCount{}
	return nil
}

func earthquakeCountAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *EarthquakeCount) error {
	*o = EarthquakeCount{}
	return nil
}

func earthquakeCountBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *EarthquakeCount) error {
	*o = EarthquakeCount{}
	return nil
}

func earthquakeCountAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *EarthquakeCount) error {
	*o = EarthquakeCount{}
	return nil
}

func earthquakeCountBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *EarthquakeCount) error {
	*o = EarthquakeCount{}
	return nil
}

func earthquakeCountAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *EarthquakeCount) error {
	*o = EarthquakeCount{}
	return nil
}

func earthquakeCountBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *EarthquakeCount) error {
	*o = EarthquakeCount{}
	return nil
}

func earthquakeCountAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *EarthquakeCount) error {
	*o = EarthquakeCount{}
	return nil
}

func testEarthquakeCountsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &EarthquakeCount{}
	o := &EarthquakeCount{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, earthquakeCountDBTypes, false); err != nil {
		t.Errorf("Unable to randomize EarthquakeCount object: %s", err)
	}

	AddEarthquakeCountHook(boil.BeforeInsertHook, earthquakeCountBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	earthquakeCountBeforeInsertHooks = []EarthquakeCountHook{}

	AddEarthquakeCountHook(boil.AfterInsertHook, earthquakeCountAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	earthquakeCountAfterInsertHooks = []EarthquakeCountHook{}

	AddEarthquakeCountHook(boil.AfterSelectHook, earthquakeCountAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	earthquakeCountAfterSelectHooks = []EarthquakeCountHook{}

	AddEarthquakeCountHook(boil.BeforeUpdateHook, earthquakeCountBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	earthquakeCountBeforeUpdateHooks = []EarthquakeCountHook{}

	AddEarthquakeCountHook(boil.AfterUpdateHook, earthquakeCountAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	earthquakeCountAfterUpdateHooks = []EarthquakeCountHook{}

	AddEarthquakeCountHook(boil.BeforeDeleteHook, earthquakeCountBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	earthquakeCountBeforeDeleteHooks = []EarthquakeCountHook{}

	AddEarthquakeCountHook(boil.AfterDeleteHook, earthquakeCountAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	earthquakeCountAfterDeleteHooks = []EarthquakeCountHook{}

	AddEarthquakeCountHook(boil.BeforeUpsertHook, earthquakeCountBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	earthquakeCountBeforeUpsertHooks = []EarthquakeCountHook{}

	AddEarthquakeCountHook(boil.AfterUpsertHook, earthquakeCountAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	earthquakeCountAfterUpsertHooks = []EarthquakeCountHook{}
}

func testEarthquakeCountsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeCount{}
	if err = randomize.Struct(seed, o, earthquakeCountDBTypes, true, earthquakeCountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeCount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := EarthquakeCounts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testEarthquakeCountsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeCount{}
	if err = randomize.Struct(seed, o, earthquakeCountDBTypes, true); err != nil {
		t.Errorf("Unable to randomize EarthquakeCount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(earthquakeCountColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := EarthquakeCounts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testEarthquakeCountsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeCount{}
	if err = randomize.Struct(seed, o, earthquakeCountDBTypes, true, earthquakeCountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeCount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testEarthquakeCountsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeCount{}
	if err = randomize.Struct(seed, o, earthquakeCountDBTypes, true, earthquakeCountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeCount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := EarthquakeCountSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testEarthquakeCountsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeCount{}
	if err = randomize.Struct(seed, o, earthquakeCountDBTypes, true, earthquakeCountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeCount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := EarthquakeCounts().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	earthquakeCountDBTypes = map[string]string{`ID`: `int`, `EventID`: `int`, `Date`: `datetime`, `Created`: `datetime`, `Row`: `text`}
	_                      = bytes.MinRead
)

func testEarthquakeCountsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(earthquakeCountPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(earthquakeCountAllColumns) == len(earthquakeCountPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeCount{}
	if err = randomize.Struct(seed, o, earthquakeCountDBTypes, true, earthquakeCountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeCount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := EarthquakeCounts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, earthquakeCountDBTypes, true, earthquakeCountPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize EarthquakeCount struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testEarthquakeCountsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(earthquakeCountAllColumns) == len(earthquakeCountPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeCount{}
	if err = randomize.Struct(seed, o, earthquakeCountDBTypes, true, earthquakeCountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeCount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := EarthquakeCounts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, earthquakeCountDBTypes, true, earthquakeCountPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize EarthquakeCount struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(earthquakeCountAllColumns, earthquakeCountPrimaryKeyColumns) {
		fields = earthquakeCountAllColumns
	} else {
		fields = strmangle.SetComplement(
			earthquakeCountAllColumns,
			earthquakeCountPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := EarthquakeCountSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testEarthquakeCountsUpsert(t *testing.T) {
	t.Parallel()

	if len(earthquakeCountAllColumns) == len(earthquakeCountPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLEarthquakeCountUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := EarthquakeCount{}
	if err = randomize.Struct(seed, &o, earthquakeCountDBTypes, false); err != nil {
		t.Errorf("Unable to randomize EarthquakeCount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert EarthquakeCount: %s", err)
	}

	count, err := EarthquakeCounts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, earthquakeCountDBTypes, false, earthquakeCountPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize EarthquakeCount struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert EarthquakeCount: %s", err)
	}

	count, err = EarthquakeCounts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
