// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testEarthquakeReports(t *testing.T) {
	t.Parallel()

	query := EarthquakeReports()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testEarthquakeReportsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeReport{}
	if err = randomize.Struct(seed, o, earthquakeReportDBTypes, true, earthquakeReportColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeReport struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := EarthquakeReports().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testEarthquakeReportsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeReport{}
	if err = randomize.Struct(seed, o, earthquakeReportDBTypes, true, earthquakeReportColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeReport struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := EarthquakeReports().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := EarthquakeReports().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testEarthquakeReportsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeReport{}
	if err = randomize.Struct(seed, o, earthquakeReportDBTypes, true, earthquakeReportColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeReport struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := EarthquakeReportSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := EarthquakeReports().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testEarthquakeReportsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeReport{}
	if err = randomize.Struct(seed, o, earthquakeReportDBTypes, true, earthquakeReportColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeReport struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := EarthquakeReportExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if EarthquakeReport exists: %s", err)
	}
	if !e {
		t.Errorf("Expected EarthquakeReportExists to return true, but got false.")
	}
}

func testEarthquakeReportsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeReport{}
	if err = randomize.Struct(seed, o, earthquakeReportDBTypes, true, earthquakeReportColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeReport struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	earthquakeReportFound, err := FindEarthquakeReport(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if earthquakeReportFound == nil {
		t.Error("want a record, got nil")
	}
}

func testEarthquakeReportsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeReport{}
	if err = randomize.Struct(seed, o, earthquakeReportDBTypes, true, earthquakeReportColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeReport struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = EarthquakeReports().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testEarthquakeReportsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeReport{}
	if err = randomize.Struct(seed, o, earthquakeReportDBTypes, true, earthquakeReportColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeReport struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := EarthquakeReports().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testEarthquakeReportsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	earthquakeReportOne := &EarthquakeReport{}
	earthquakeReportTwo := &EarthquakeReport{}
	if err = randomize.Struct(seed, earthquakeReportOne, earthquakeReportDBTypes, false, earthquakeReportColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeReport struct: %s", err)
	}
	if err = randomize.Struct(seed, earthquakeReportTwo, earthquakeReportDBTypes, false, earthquakeReportColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeReport struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = earthquakeReportOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = earthquakeReportTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := EarthquakeReports().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testEarthquakeReportsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	earthquakeReportOne := &EarthquakeReport{}
	earthquakeReportTwo := &EarthquakeReport{}
	if err = randomize.Struct(seed, earthquakeReportOne, earthquakeReportDBTypes, false, earthquakeReportColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeReport struct: %s", err)
	}
	if err = randomize.Struct(seed, earthquakeReportTwo, earthquakeReportDBTypes, false, earthquakeReportColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeReport struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = earthquakeReportOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = earthquakeReportTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := EarthquakeReports().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func earthquakeReportBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *EarthquakeReport) error {
	*o = EarthquakeReport{}
	return nil
}

func earthquakeReportAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *EarthquakeReport) error {
	*o = EarthquakeReport{}
	return nil
}

func earthquakeReportAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *EarthquakeReport) error {
	*o = EarthquakeReport{}
	return nil
}

func earthquakeReportBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *EarthquakeReport) error {
	*o = EarthquakeReport{}
	return nil
}

func earthquakeReportAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *EarthquakeReport) error {
	*o = EarthquakeReport{}
	return nil
}

func earthquakeReportBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *EarthquakeReport) error {
	*o = EarthquakeReport{}
	return nil
}

func earthquakeReportAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *EarthquakeReport) error {
	*o = EarthquakeReport{}
	return nil
}

func earthquakeReportBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *EarthquakeReport) error {
	*o = EarthquakeReport{}
	return nil
}

func earthquakeReportAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *EarthquakeReport) error {
	*o = EarthquakeReport{}
	return nil
}

func testEarthquakeReportsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &EarthquakeReport{}
	o := &EarthquakeReport{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, earthquakeReportDBTypes, false); err != nil {
		t.Errorf("Unable to randomize EarthquakeReport object: %s", err)
	}

	AddEarthquakeReportHook(boil.BeforeInsertHook, earthquakeReportBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	earthquakeReportBeforeInsertHooks = []EarthquakeReportHook{}

	AddEarthquakeReportHook(boil.AfterInsertHook, earthquakeReportAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	earthquakeReportAfterInsertHooks = []EarthquakeReportHook{}

	AddEarthquakeReportHook(boil.AfterSelectHook, earthquakeReportAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	earthquakeReportAfterSelectHooks = []EarthquakeReportHook{}

	AddEarthquakeReportHook(boil.BeforeUpdateHook, earthquakeReportBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	earthquakeReportBeforeUpdateHooks = []EarthquakeReportHook{}

	AddEarthquakeReportHook(boil.AfterUpdateHook, earthquakeReportAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	earthquakeReportAfterUpdateHooks = []EarthquakeReportHook{}

	AddEarthquakeReportHook(boil.BeforeDeleteHook, earthquakeReportBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	earthquakeReportBeforeDeleteHooks = []EarthquakeReportHook{}

	AddEarthquakeReportHook(boil.AfterDeleteHook, earthquakeReportAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	earthquakeReportAfterDeleteHooks = []EarthquakeReportHook{}

	AddEarthquakeReportHook(boil.BeforeUpsertHook, earthquakeReportBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	earthquakeReportBeforeUpsertHooks = []EarthquakeReportHook{}

	AddEarthquakeReportHook(boil.AfterUpsertHook, earthquakeReportAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	earthquakeReportAfterUpsertHooks = []EarthquakeReportHook{}
}

func testEarthquakeReportsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeReport{}
	if err = randomize.Struct(seed, o, earthquakeReportDBTypes, true, earthquakeReportColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeReport struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := EarthquakeReports().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testEarthquakeReportsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeReport{}
	if err = randomize.Struct(seed, o, earthquakeReportDBTypes, true); err != nil {
		t.Errorf("Unable to randomize EarthquakeReport struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(earthquakeReportColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := EarthquakeReports().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testEarthquakeReportsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeReport{}
	if err = randomize.Struct(seed, o, earthquakeReportDBTypes, true, earthquakeReportColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeReport struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testEarthquakeReportsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeReport{}
	if err = randomize.Struct(seed, o, earthquakeReportDBTypes, true, earthquakeReportColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeReport struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := EarthquakeReportSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testEarthquakeReportsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeReport{}
	if err = randomize.Struct(seed, o, earthquakeReportDBTypes, true, earthquakeReportColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeReport struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := EarthquakeReports().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	earthquakeReportDBTypes = map[string]string{`ID`: `int`, `EventID`: `bigint`, `MaxInt`: `varchar`, `Date`: `datetime`, `Created`: `datetime`, `Row`: `text`}
	_                       = bytes.MinRead
)

func testEarthquakeReportsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(earthquakeReportPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(earthquakeReportAllColumns) == len(earthquakeReportPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeReport{}
	if err = randomize.Struct(seed, o, earthquakeReportDBTypes, true, earthquakeReportColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeReport struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := EarthquakeReports().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, earthquakeReportDBTypes, true, earthquakeReportPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize EarthquakeReport struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testEarthquakeReportsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(earthquakeReportAllColumns) == len(earthquakeReportPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeReport{}
	if err = randomize.Struct(seed, o, earthquakeReportDBTypes, true, earthquakeReportColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeReport struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := EarthquakeReports().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, earthquakeReportDBTypes, true, earthquakeReportPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize EarthquakeReport struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(earthquakeReportAllColumns, earthquakeReportPrimaryKeyColumns) {
		fields = earthquakeReportAllColumns
	} else {
		fields = strmangle.SetComplement(
			earthquakeReportAllColumns,
			earthquakeReportPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := EarthquakeReportSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testEarthquakeReportsUpsert(t *testing.T) {
	t.Parallel()

	if len(earthquakeReportAllColumns) == len(earthquakeReportPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLEarthquakeReportUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := EarthquakeReport{}
	if err = randomize.Struct(seed, &o, earthquakeReportDBTypes, false); err != nil {
		t.Errorf("Unable to randomize EarthquakeReport struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert EarthquakeReport: %s", err)
	}

	count, err := EarthquakeReports().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, earthquakeReportDBTypes, false, earthquakeReportPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize EarthquakeReport struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert EarthquakeReport: %s", err)
	}

	count, err = EarthquakeReports().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
