// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testEarthquakeActivities(t *testing.T) {
	t.Parallel()

	query := EarthquakeActivities()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testEarthquakeActivitiesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeActivity{}
	if err = randomize.Struct(seed, o, earthquakeActivityDBTypes, true, earthquakeActivityColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeActivity struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := EarthquakeActivities().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testEarthquakeActivitiesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeActivity{}
	if err = randomize.Struct(seed, o, earthquakeActivityDBTypes, true, earthquakeActivityColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeActivity struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := EarthquakeActivities().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := EarthquakeActivities().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testEarthquakeActivitiesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeActivity{}
	if err = randomize.Struct(seed, o, earthquakeActivityDBTypes, true, earthquakeActivityColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeActivity struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := EarthquakeActivitySlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := EarthquakeActivities().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testEarthquakeActivitiesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeActivity{}
	if err = randomize.Struct(seed, o, earthquakeActivityDBTypes, true, earthquakeActivityColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeActivity struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := EarthquakeActivityExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if EarthquakeActivity exists: %s", err)
	}
	if !e {
		t.Errorf("Expected EarthquakeActivityExists to return true, but got false.")
	}
}

func testEarthquakeActivitiesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeActivity{}
	if err = randomize.Struct(seed, o, earthquakeActivityDBTypes, true, earthquakeActivityColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeActivity struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	earthquakeActivityFound, err := FindEarthquakeActivity(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if earthquakeActivityFound == nil {
		t.Error("want a record, got nil")
	}
}

func testEarthquakeActivitiesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeActivity{}
	if err = randomize.Struct(seed, o, earthquakeActivityDBTypes, true, earthquakeActivityColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeActivity struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = EarthquakeActivities().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testEarthquakeActivitiesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeActivity{}
	if err = randomize.Struct(seed, o, earthquakeActivityDBTypes, true, earthquakeActivityColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeActivity struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := EarthquakeActivities().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testEarthquakeActivitiesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	earthquakeActivityOne := &EarthquakeActivity{}
	earthquakeActivityTwo := &EarthquakeActivity{}
	if err = randomize.Struct(seed, earthquakeActivityOne, earthquakeActivityDBTypes, false, earthquakeActivityColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeActivity struct: %s", err)
	}
	if err = randomize.Struct(seed, earthquakeActivityTwo, earthquakeActivityDBTypes, false, earthquakeActivityColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeActivity struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = earthquakeActivityOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = earthquakeActivityTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := EarthquakeActivities().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testEarthquakeActivitiesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	earthquakeActivityOne := &EarthquakeActivity{}
	earthquakeActivityTwo := &EarthquakeActivity{}
	if err = randomize.Struct(seed, earthquakeActivityOne, earthquakeActivityDBTypes, false, earthquakeActivityColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeActivity struct: %s", err)
	}
	if err = randomize.Struct(seed, earthquakeActivityTwo, earthquakeActivityDBTypes, false, earthquakeActivityColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeActivity struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = earthquakeActivityOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = earthquakeActivityTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := EarthquakeActivities().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func earthquakeActivityBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *EarthquakeActivity) error {
	*o = EarthquakeActivity{}
	return nil
}

func earthquakeActivityAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *EarthquakeActivity) error {
	*o = EarthquakeActivity{}
	return nil
}

func earthquakeActivityAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *EarthquakeActivity) error {
	*o = EarthquakeActivity{}
	return nil
}

func earthquakeActivityBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *EarthquakeActivity) error {
	*o = EarthquakeActivity{}
	return nil
}

func earthquakeActivityAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *EarthquakeActivity) error {
	*o = EarthquakeActivity{}
	return nil
}

func earthquakeActivityBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *EarthquakeActivity) error {
	*o = EarthquakeActivity{}
	return nil
}

func earthquakeActivityAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *EarthquakeActivity) error {
	*o = EarthquakeActivity{}
	return nil
}

func earthquakeActivityBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *EarthquakeActivity) error {
	*o = EarthquakeActivity{}
	return nil
}

func earthquakeActivityAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *EarthquakeActivity) error {
	*o = EarthquakeActivity{}
	return nil
}

func testEarthquakeActivitiesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &EarthquakeActivity{}
	o := &EarthquakeActivity{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, earthquakeActivityDBTypes, false); err != nil {
		t.Errorf("Unable to randomize EarthquakeActivity object: %s", err)
	}

	AddEarthquakeActivityHook(boil.BeforeInsertHook, earthquakeActivityBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	earthquakeActivityBeforeInsertHooks = []EarthquakeActivityHook{}

	AddEarthquakeActivityHook(boil.AfterInsertHook, earthquakeActivityAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	earthquakeActivityAfterInsertHooks = []EarthquakeActivityHook{}

	AddEarthquakeActivityHook(boil.AfterSelectHook, earthquakeActivityAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	earthquakeActivityAfterSelectHooks = []EarthquakeActivityHook{}

	AddEarthquakeActivityHook(boil.BeforeUpdateHook, earthquakeActivityBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	earthquakeActivityBeforeUpdateHooks = []EarthquakeActivityHook{}

	AddEarthquakeActivityHook(boil.AfterUpdateHook, earthquakeActivityAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	earthquakeActivityAfterUpdateHooks = []EarthquakeActivityHook{}

	AddEarthquakeActivityHook(boil.BeforeDeleteHook, earthquakeActivityBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	earthquakeActivityBeforeDeleteHooks = []EarthquakeActivityHook{}

	AddEarthquakeActivityHook(boil.AfterDeleteHook, earthquakeActivityAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	earthquakeActivityAfterDeleteHooks = []EarthquakeActivityHook{}

	AddEarthquakeActivityHook(boil.BeforeUpsertHook, earthquakeActivityBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	earthquakeActivityBeforeUpsertHooks = []EarthquakeActivityHook{}

	AddEarthquakeActivityHook(boil.AfterUpsertHook, earthquakeActivityAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	earthquakeActivityAfterUpsertHooks = []EarthquakeActivityHook{}
}

func testEarthquakeActivitiesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeActivity{}
	if err = randomize.Struct(seed, o, earthquakeActivityDBTypes, true, earthquakeActivityColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeActivity struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := EarthquakeActivities().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testEarthquakeActivitiesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeActivity{}
	if err = randomize.Struct(seed, o, earthquakeActivityDBTypes, true); err != nil {
		t.Errorf("Unable to randomize EarthquakeActivity struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(earthquakeActivityColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := EarthquakeActivities().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testEarthquakeActivitiesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeActivity{}
	if err = randomize.Struct(seed, o, earthquakeActivityDBTypes, true, earthquakeActivityColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeActivity struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testEarthquakeActivitiesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeActivity{}
	if err = randomize.Struct(seed, o, earthquakeActivityDBTypes, true, earthquakeActivityColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeActivity struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := EarthquakeActivitySlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testEarthquakeActivitiesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeActivity{}
	if err = randomize.Struct(seed, o, earthquakeActivityDBTypes, true, earthquakeActivityColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeActivity struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := EarthquakeActivities().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	earthquakeActivityDBTypes = map[string]string{`ID`: `int`, `EventID`: `int`, `Date`: `datetime`, `Created`: `datetime`, `Row`: `text`}
	_                         = bytes.MinRead
)

func testEarthquakeActivitiesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(earthquakeActivityPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(earthquakeActivityAllColumns) == len(earthquakeActivityPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeActivity{}
	if err = randomize.Struct(seed, o, earthquakeActivityDBTypes, true, earthquakeActivityColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeActivity struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := EarthquakeActivities().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, earthquakeActivityDBTypes, true, earthquakeActivityPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize EarthquakeActivity struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testEarthquakeActivitiesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(earthquakeActivityAllColumns) == len(earthquakeActivityPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &EarthquakeActivity{}
	if err = randomize.Struct(seed, o, earthquakeActivityDBTypes, true, earthquakeActivityColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize EarthquakeActivity struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := EarthquakeActivities().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, earthquakeActivityDBTypes, true, earthquakeActivityPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize EarthquakeActivity struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(earthquakeActivityAllColumns, earthquakeActivityPrimaryKeyColumns) {
		fields = earthquakeActivityAllColumns
	} else {
		fields = strmangle.SetComplement(
			earthquakeActivityAllColumns,
			earthquakeActivityPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := EarthquakeActivitySlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testEarthquakeActivitiesUpsert(t *testing.T) {
	t.Parallel()

	if len(earthquakeActivityAllColumns) == len(earthquakeActivityPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLEarthquakeActivityUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := EarthquakeActivity{}
	if err = randomize.Struct(seed, &o, earthquakeActivityDBTypes, false); err != nil {
		t.Errorf("Unable to randomize EarthquakeActivity struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert EarthquakeActivity: %s", err)
	}

	count, err := EarthquakeActivities().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, earthquakeActivityDBTypes, false, earthquakeActivityPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize EarthquakeActivity struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert EarthquakeActivity: %s", err)
	}

	count, err = EarthquakeActivities().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
