// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testJmaXmlEntries(t *testing.T) {
	t.Parallel()

	query := JmaXmlEntries()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testJmaXmlEntriesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JmaXmlEntry{}
	if err = randomize.Struct(seed, o, jmaXmlEntryDBTypes, true, jmaXmlEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JmaXmlEntry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := JmaXmlEntries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testJmaXmlEntriesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JmaXmlEntry{}
	if err = randomize.Struct(seed, o, jmaXmlEntryDBTypes, true, jmaXmlEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JmaXmlEntry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := JmaXmlEntries().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := JmaXmlEntries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testJmaXmlEntriesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JmaXmlEntry{}
	if err = randomize.Struct(seed, o, jmaXmlEntryDBTypes, true, jmaXmlEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JmaXmlEntry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := JmaXmlEntrySlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := JmaXmlEntries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testJmaXmlEntriesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JmaXmlEntry{}
	if err = randomize.Struct(seed, o, jmaXmlEntryDBTypes, true, jmaXmlEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JmaXmlEntry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := JmaXmlEntryExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if JmaXmlEntry exists: %s", err)
	}
	if !e {
		t.Errorf("Expected JmaXmlEntryExists to return true, but got false.")
	}
}

func testJmaXmlEntriesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JmaXmlEntry{}
	if err = randomize.Struct(seed, o, jmaXmlEntryDBTypes, true, jmaXmlEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JmaXmlEntry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	jmaXmlEntryFound, err := FindJmaXmlEntry(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if jmaXmlEntryFound == nil {
		t.Error("want a record, got nil")
	}
}

func testJmaXmlEntriesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JmaXmlEntry{}
	if err = randomize.Struct(seed, o, jmaXmlEntryDBTypes, true, jmaXmlEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JmaXmlEntry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = JmaXmlEntries().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testJmaXmlEntriesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JmaXmlEntry{}
	if err = randomize.Struct(seed, o, jmaXmlEntryDBTypes, true, jmaXmlEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JmaXmlEntry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := JmaXmlEntries().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testJmaXmlEntriesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	jmaXmlEntryOne := &JmaXmlEntry{}
	jmaXmlEntryTwo := &JmaXmlEntry{}
	if err = randomize.Struct(seed, jmaXmlEntryOne, jmaXmlEntryDBTypes, false, jmaXmlEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JmaXmlEntry struct: %s", err)
	}
	if err = randomize.Struct(seed, jmaXmlEntryTwo, jmaXmlEntryDBTypes, false, jmaXmlEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JmaXmlEntry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = jmaXmlEntryOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = jmaXmlEntryTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := JmaXmlEntries().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testJmaXmlEntriesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	jmaXmlEntryOne := &JmaXmlEntry{}
	jmaXmlEntryTwo := &JmaXmlEntry{}
	if err = randomize.Struct(seed, jmaXmlEntryOne, jmaXmlEntryDBTypes, false, jmaXmlEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JmaXmlEntry struct: %s", err)
	}
	if err = randomize.Struct(seed, jmaXmlEntryTwo, jmaXmlEntryDBTypes, false, jmaXmlEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JmaXmlEntry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = jmaXmlEntryOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = jmaXmlEntryTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := JmaXmlEntries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func jmaXmlEntryBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *JmaXmlEntry) error {
	*o = JmaXmlEntry{}
	return nil
}

func jmaXmlEntryAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *JmaXmlEntry) error {
	*o = JmaXmlEntry{}
	return nil
}

func jmaXmlEntryAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *JmaXmlEntry) error {
	*o = JmaXmlEntry{}
	return nil
}

func jmaXmlEntryBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *JmaXmlEntry) error {
	*o = JmaXmlEntry{}
	return nil
}

func jmaXmlEntryAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *JmaXmlEntry) error {
	*o = JmaXmlEntry{}
	return nil
}

func jmaXmlEntryBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *JmaXmlEntry) error {
	*o = JmaXmlEntry{}
	return nil
}

func jmaXmlEntryAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *JmaXmlEntry) error {
	*o = JmaXmlEntry{}
	return nil
}

func jmaXmlEntryBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *JmaXmlEntry) error {
	*o = JmaXmlEntry{}
	return nil
}

func jmaXmlEntryAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *JmaXmlEntry) error {
	*o = JmaXmlEntry{}
	return nil
}

func testJmaXmlEntriesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &JmaXmlEntry{}
	o := &JmaXmlEntry{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, jmaXmlEntryDBTypes, false); err != nil {
		t.Errorf("Unable to randomize JmaXmlEntry object: %s", err)
	}

	AddJmaXmlEntryHook(boil.BeforeInsertHook, jmaXmlEntryBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	jmaXmlEntryBeforeInsertHooks = []JmaXmlEntryHook{}

	AddJmaXmlEntryHook(boil.AfterInsertHook, jmaXmlEntryAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	jmaXmlEntryAfterInsertHooks = []JmaXmlEntryHook{}

	AddJmaXmlEntryHook(boil.AfterSelectHook, jmaXmlEntryAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	jmaXmlEntryAfterSelectHooks = []JmaXmlEntryHook{}

	AddJmaXmlEntryHook(boil.BeforeUpdateHook, jmaXmlEntryBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	jmaXmlEntryBeforeUpdateHooks = []JmaXmlEntryHook{}

	AddJmaXmlEntryHook(boil.AfterUpdateHook, jmaXmlEntryAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	jmaXmlEntryAfterUpdateHooks = []JmaXmlEntryHook{}

	AddJmaXmlEntryHook(boil.BeforeDeleteHook, jmaXmlEntryBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	jmaXmlEntryBeforeDeleteHooks = []JmaXmlEntryHook{}

	AddJmaXmlEntryHook(boil.AfterDeleteHook, jmaXmlEntryAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	jmaXmlEntryAfterDeleteHooks = []JmaXmlEntryHook{}

	AddJmaXmlEntryHook(boil.BeforeUpsertHook, jmaXmlEntryBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	jmaXmlEntryBeforeUpsertHooks = []JmaXmlEntryHook{}

	AddJmaXmlEntryHook(boil.AfterUpsertHook, jmaXmlEntryAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	jmaXmlEntryAfterUpsertHooks = []JmaXmlEntryHook{}
}

func testJmaXmlEntriesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JmaXmlEntry{}
	if err = randomize.Struct(seed, o, jmaXmlEntryDBTypes, true, jmaXmlEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JmaXmlEntry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := JmaXmlEntries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testJmaXmlEntriesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JmaXmlEntry{}
	if err = randomize.Struct(seed, o, jmaXmlEntryDBTypes, true); err != nil {
		t.Errorf("Unable to randomize JmaXmlEntry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(jmaXmlEntryColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := JmaXmlEntries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testJmaXmlEntriesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JmaXmlEntry{}
	if err = randomize.Struct(seed, o, jmaXmlEntryDBTypes, true, jmaXmlEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JmaXmlEntry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testJmaXmlEntriesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JmaXmlEntry{}
	if err = randomize.Struct(seed, o, jmaXmlEntryDBTypes, true, jmaXmlEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JmaXmlEntry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := JmaXmlEntrySlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testJmaXmlEntriesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &JmaXmlEntry{}
	if err = randomize.Struct(seed, o, jmaXmlEntryDBTypes, true, jmaXmlEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JmaXmlEntry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := JmaXmlEntries().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	jmaXmlEntryDBTypes = map[string]string{`ID`: `varchar`, `Updated`: `datetime`, `Created`: `datetime`}
	_                  = bytes.MinRead
)

func testJmaXmlEntriesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(jmaXmlEntryPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(jmaXmlEntryAllColumns) == len(jmaXmlEntryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &JmaXmlEntry{}
	if err = randomize.Struct(seed, o, jmaXmlEntryDBTypes, true, jmaXmlEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JmaXmlEntry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := JmaXmlEntries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, jmaXmlEntryDBTypes, true, jmaXmlEntryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize JmaXmlEntry struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testJmaXmlEntriesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(jmaXmlEntryAllColumns) == len(jmaXmlEntryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &JmaXmlEntry{}
	if err = randomize.Struct(seed, o, jmaXmlEntryDBTypes, true, jmaXmlEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize JmaXmlEntry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := JmaXmlEntries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, jmaXmlEntryDBTypes, true, jmaXmlEntryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize JmaXmlEntry struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(jmaXmlEntryAllColumns, jmaXmlEntryPrimaryKeyColumns) {
		fields = jmaXmlEntryAllColumns
	} else {
		fields = strmangle.SetComplement(
			jmaXmlEntryAllColumns,
			jmaXmlEntryPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := JmaXmlEntrySlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testJmaXmlEntriesUpsert(t *testing.T) {
	t.Parallel()

	if len(jmaXmlEntryAllColumns) == len(jmaXmlEntryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLJmaXmlEntryUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := JmaXmlEntry{}
	if err = randomize.Struct(seed, &o, jmaXmlEntryDBTypes, false); err != nil {
		t.Errorf("Unable to randomize JmaXmlEntry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert JmaXmlEntry: %s", err)
	}

	count, err := JmaXmlEntries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, jmaXmlEntryDBTypes, false, jmaXmlEntryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize JmaXmlEntry struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert JmaXmlEntry: %s", err)
	}

	count, err = JmaXmlEntries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
