// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// JmaXmlEntry is an object representing the database table.
type JmaXmlEntry struct {
	ID      string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	Updated time.Time `boil:"updated" json:"updated" toml:"updated" yaml:"updated"`
	Created time.Time `boil:"created" json:"created" toml:"created" yaml:"created"`

	R *jmaXmlEntryR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L jmaXmlEntryL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var JmaXmlEntryColumns = struct {
	ID      string
	Updated string
	Created string
}{
	ID:      "id",
	Updated: "updated",
	Created: "created",
}

var JmaXmlEntryTableColumns = struct {
	ID      string
	Updated string
	Created string
}{
	ID:      "JmaXmlEntries.id",
	Updated: "JmaXmlEntries.updated",
	Created: "JmaXmlEntries.created",
}

// Generated where

var JmaXmlEntryWhere = struct {
	ID      whereHelperstring
	Updated whereHelpertime_Time
	Created whereHelpertime_Time
}{
	ID:      whereHelperstring{field: "`JmaXmlEntries`.`id`"},
	Updated: whereHelpertime_Time{field: "`JmaXmlEntries`.`updated`"},
	Created: whereHelpertime_Time{field: "`JmaXmlEntries`.`created`"},
}

// JmaXmlEntryRels is where relationship names are stored.
var JmaXmlEntryRels = struct {
}{}

// jmaXmlEntryR is where relationships are stored.
type jmaXmlEntryR struct {
}

// NewStruct creates a new relationship struct
func (*jmaXmlEntryR) NewStruct() *jmaXmlEntryR {
	return &jmaXmlEntryR{}
}

// jmaXmlEntryL is where Load methods for each relationship are stored.
type jmaXmlEntryL struct{}

var (
	jmaXmlEntryAllColumns            = []string{"id", "updated", "created"}
	jmaXmlEntryColumnsWithoutDefault = []string{"id", "updated"}
	jmaXmlEntryColumnsWithDefault    = []string{"created"}
	jmaXmlEntryPrimaryKeyColumns     = []string{"id"}
	jmaXmlEntryGeneratedColumns      = []string{}
)

type (
	// JmaXmlEntrySlice is an alias for a slice of pointers to JmaXmlEntry.
	// This should almost always be used instead of []JmaXmlEntry.
	JmaXmlEntrySlice []*JmaXmlEntry
	// JmaXmlEntryHook is the signature for custom JmaXmlEntry hook methods
	JmaXmlEntryHook func(context.Context, boil.ContextExecutor, *JmaXmlEntry) error

	jmaXmlEntryQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	jmaXmlEntryType                 = reflect.TypeOf(&JmaXmlEntry{})
	jmaXmlEntryMapping              = queries.MakeStructMapping(jmaXmlEntryType)
	jmaXmlEntryPrimaryKeyMapping, _ = queries.BindMapping(jmaXmlEntryType, jmaXmlEntryMapping, jmaXmlEntryPrimaryKeyColumns)
	jmaXmlEntryInsertCacheMut       sync.RWMutex
	jmaXmlEntryInsertCache          = make(map[string]insertCache)
	jmaXmlEntryUpdateCacheMut       sync.RWMutex
	jmaXmlEntryUpdateCache          = make(map[string]updateCache)
	jmaXmlEntryUpsertCacheMut       sync.RWMutex
	jmaXmlEntryUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var jmaXmlEntryAfterSelectHooks []JmaXmlEntryHook

var jmaXmlEntryBeforeInsertHooks []JmaXmlEntryHook
var jmaXmlEntryAfterInsertHooks []JmaXmlEntryHook

var jmaXmlEntryBeforeUpdateHooks []JmaXmlEntryHook
var jmaXmlEntryAfterUpdateHooks []JmaXmlEntryHook

var jmaXmlEntryBeforeDeleteHooks []JmaXmlEntryHook
var jmaXmlEntryAfterDeleteHooks []JmaXmlEntryHook

var jmaXmlEntryBeforeUpsertHooks []JmaXmlEntryHook
var jmaXmlEntryAfterUpsertHooks []JmaXmlEntryHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *JmaXmlEntry) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range jmaXmlEntryAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *JmaXmlEntry) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range jmaXmlEntryBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *JmaXmlEntry) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range jmaXmlEntryAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *JmaXmlEntry) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range jmaXmlEntryBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *JmaXmlEntry) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range jmaXmlEntryAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *JmaXmlEntry) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range jmaXmlEntryBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *JmaXmlEntry) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range jmaXmlEntryAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *JmaXmlEntry) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range jmaXmlEntryBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *JmaXmlEntry) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range jmaXmlEntryAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddJmaXmlEntryHook registers your hook function for all future operations.
func AddJmaXmlEntryHook(hookPoint boil.HookPoint, jmaXmlEntryHook JmaXmlEntryHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		jmaXmlEntryAfterSelectHooks = append(jmaXmlEntryAfterSelectHooks, jmaXmlEntryHook)
	case boil.BeforeInsertHook:
		jmaXmlEntryBeforeInsertHooks = append(jmaXmlEntryBeforeInsertHooks, jmaXmlEntryHook)
	case boil.AfterInsertHook:
		jmaXmlEntryAfterInsertHooks = append(jmaXmlEntryAfterInsertHooks, jmaXmlEntryHook)
	case boil.BeforeUpdateHook:
		jmaXmlEntryBeforeUpdateHooks = append(jmaXmlEntryBeforeUpdateHooks, jmaXmlEntryHook)
	case boil.AfterUpdateHook:
		jmaXmlEntryAfterUpdateHooks = append(jmaXmlEntryAfterUpdateHooks, jmaXmlEntryHook)
	case boil.BeforeDeleteHook:
		jmaXmlEntryBeforeDeleteHooks = append(jmaXmlEntryBeforeDeleteHooks, jmaXmlEntryHook)
	case boil.AfterDeleteHook:
		jmaXmlEntryAfterDeleteHooks = append(jmaXmlEntryAfterDeleteHooks, jmaXmlEntryHook)
	case boil.BeforeUpsertHook:
		jmaXmlEntryBeforeUpsertHooks = append(jmaXmlEntryBeforeUpsertHooks, jmaXmlEntryHook)
	case boil.AfterUpsertHook:
		jmaXmlEntryAfterUpsertHooks = append(jmaXmlEntryAfterUpsertHooks, jmaXmlEntryHook)
	}
}

// One returns a single jmaXmlEntry record from the query.
func (q jmaXmlEntryQuery) One(ctx context.Context, exec boil.ContextExecutor) (*JmaXmlEntry, error) {
	o := &JmaXmlEntry{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for JmaXmlEntries")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all JmaXmlEntry records from the query.
func (q jmaXmlEntryQuery) All(ctx context.Context, exec boil.ContextExecutor) (JmaXmlEntrySlice, error) {
	var o []*JmaXmlEntry

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to JmaXmlEntry slice")
	}

	if len(jmaXmlEntryAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all JmaXmlEntry records in the query.
func (q jmaXmlEntryQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count JmaXmlEntries rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q jmaXmlEntryQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if JmaXmlEntries exists")
	}

	return count > 0, nil
}

// JmaXmlEntries retrieves all the records using an executor.
func JmaXmlEntries(mods ...qm.QueryMod) jmaXmlEntryQuery {
	mods = append(mods, qm.From("`JmaXmlEntries`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`JmaXmlEntries`.*"})
	}

	return jmaXmlEntryQuery{q}
}

// FindJmaXmlEntry retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindJmaXmlEntry(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*JmaXmlEntry, error) {
	jmaXmlEntryObj := &JmaXmlEntry{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `JmaXmlEntries` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, jmaXmlEntryObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from JmaXmlEntries")
	}

	if err = jmaXmlEntryObj.doAfterSelectHooks(ctx, exec); err != nil {
		return jmaXmlEntryObj, err
	}

	return jmaXmlEntryObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *JmaXmlEntry) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no JmaXmlEntries provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(jmaXmlEntryColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	jmaXmlEntryInsertCacheMut.RLock()
	cache, cached := jmaXmlEntryInsertCache[key]
	jmaXmlEntryInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			jmaXmlEntryAllColumns,
			jmaXmlEntryColumnsWithDefault,
			jmaXmlEntryColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(jmaXmlEntryType, jmaXmlEntryMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(jmaXmlEntryType, jmaXmlEntryMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `JmaXmlEntries` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `JmaXmlEntries` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `JmaXmlEntries` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, jmaXmlEntryPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into JmaXmlEntries")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for JmaXmlEntries")
	}

CacheNoHooks:
	if !cached {
		jmaXmlEntryInsertCacheMut.Lock()
		jmaXmlEntryInsertCache[key] = cache
		jmaXmlEntryInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the JmaXmlEntry.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *JmaXmlEntry) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	jmaXmlEntryUpdateCacheMut.RLock()
	cache, cached := jmaXmlEntryUpdateCache[key]
	jmaXmlEntryUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			jmaXmlEntryAllColumns,
			jmaXmlEntryPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update JmaXmlEntries, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `JmaXmlEntries` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, jmaXmlEntryPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(jmaXmlEntryType, jmaXmlEntryMapping, append(wl, jmaXmlEntryPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update JmaXmlEntries row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for JmaXmlEntries")
	}

	if !cached {
		jmaXmlEntryUpdateCacheMut.Lock()
		jmaXmlEntryUpdateCache[key] = cache
		jmaXmlEntryUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q jmaXmlEntryQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for JmaXmlEntries")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for JmaXmlEntries")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o JmaXmlEntrySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), jmaXmlEntryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `JmaXmlEntries` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, jmaXmlEntryPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in jmaXmlEntry slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all jmaXmlEntry")
	}
	return rowsAff, nil
}

var mySQLJmaXmlEntryUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *JmaXmlEntry) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no JmaXmlEntries provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(jmaXmlEntryColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLJmaXmlEntryUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	jmaXmlEntryUpsertCacheMut.RLock()
	cache, cached := jmaXmlEntryUpsertCache[key]
	jmaXmlEntryUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			jmaXmlEntryAllColumns,
			jmaXmlEntryColumnsWithDefault,
			jmaXmlEntryColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			jmaXmlEntryAllColumns,
			jmaXmlEntryPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert JmaXmlEntries, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`JmaXmlEntries`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `JmaXmlEntries` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(jmaXmlEntryType, jmaXmlEntryMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(jmaXmlEntryType, jmaXmlEntryMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for JmaXmlEntries")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(jmaXmlEntryType, jmaXmlEntryMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for JmaXmlEntries")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for JmaXmlEntries")
	}

CacheNoHooks:
	if !cached {
		jmaXmlEntryUpsertCacheMut.Lock()
		jmaXmlEntryUpsertCache[key] = cache
		jmaXmlEntryUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single JmaXmlEntry record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *JmaXmlEntry) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no JmaXmlEntry provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), jmaXmlEntryPrimaryKeyMapping)
	sql := "DELETE FROM `JmaXmlEntries` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from JmaXmlEntries")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for JmaXmlEntries")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q jmaXmlEntryQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no jmaXmlEntryQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from JmaXmlEntries")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for JmaXmlEntries")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o JmaXmlEntrySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(jmaXmlEntryBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), jmaXmlEntryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `JmaXmlEntries` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, jmaXmlEntryPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from jmaXmlEntry slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for JmaXmlEntries")
	}

	if len(jmaXmlEntryAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *JmaXmlEntry) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindJmaXmlEntry(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *JmaXmlEntrySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := JmaXmlEntrySlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), jmaXmlEntryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `JmaXmlEntries`.* FROM `JmaXmlEntries` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, jmaXmlEntryPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in JmaXmlEntrySlice")
	}

	*o = slice

	return nil
}

// JmaXmlEntryExists checks if the JmaXmlEntry row exists.
func JmaXmlEntryExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `JmaXmlEntries` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if JmaXmlEntries exists")
	}

	return exists, nil
}

// Exists checks if the JmaXmlEntry row exists.
func (o *JmaXmlEntry) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return JmaXmlEntryExists(ctx, exec, o.ID)
}
