// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// PrefectureCode is an object representing the database table.
type PrefectureCode struct {
	ID      uint      `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name    string    `boil:"name" json:"name" toml:"name" yaml:"name"`
	Created time.Time `boil:"created" json:"created" toml:"created" yaml:"created"`
	Updated time.Time `boil:"updated" json:"updated" toml:"updated" yaml:"updated"`

	R *prefectureCodeR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L prefectureCodeL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PrefectureCodeColumns = struct {
	ID      string
	Name    string
	Created string
	Updated string
}{
	ID:      "id",
	Name:    "name",
	Created: "created",
	Updated: "updated",
}

var PrefectureCodeTableColumns = struct {
	ID      string
	Name    string
	Created string
	Updated string
}{
	ID:      "PrefectureCodes.id",
	Name:    "PrefectureCodes.name",
	Created: "PrefectureCodes.created",
	Updated: "PrefectureCodes.updated",
}

// Generated where

var PrefectureCodeWhere = struct {
	ID      whereHelperuint
	Name    whereHelperstring
	Created whereHelpertime_Time
	Updated whereHelpertime_Time
}{
	ID:      whereHelperuint{field: "`PrefectureCodes`.`id`"},
	Name:    whereHelperstring{field: "`PrefectureCodes`.`name`"},
	Created: whereHelpertime_Time{field: "`PrefectureCodes`.`created`"},
	Updated: whereHelpertime_Time{field: "`PrefectureCodes`.`updated`"},
}

// PrefectureCodeRels is where relationship names are stored.
var PrefectureCodeRels = struct {
}{}

// prefectureCodeR is where relationships are stored.
type prefectureCodeR struct {
}

// NewStruct creates a new relationship struct
func (*prefectureCodeR) NewStruct() *prefectureCodeR {
	return &prefectureCodeR{}
}

// prefectureCodeL is where Load methods for each relationship are stored.
type prefectureCodeL struct{}

var (
	prefectureCodeAllColumns            = []string{"id", "name", "created", "updated"}
	prefectureCodeColumnsWithoutDefault = []string{"id", "name"}
	prefectureCodeColumnsWithDefault    = []string{"created", "updated"}
	prefectureCodePrimaryKeyColumns     = []string{"id"}
	prefectureCodeGeneratedColumns      = []string{}
)

type (
	// PrefectureCodeSlice is an alias for a slice of pointers to PrefectureCode.
	// This should almost always be used instead of []PrefectureCode.
	PrefectureCodeSlice []*PrefectureCode
	// PrefectureCodeHook is the signature for custom PrefectureCode hook methods
	PrefectureCodeHook func(context.Context, boil.ContextExecutor, *PrefectureCode) error

	prefectureCodeQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	prefectureCodeType                 = reflect.TypeOf(&PrefectureCode{})
	prefectureCodeMapping              = queries.MakeStructMapping(prefectureCodeType)
	prefectureCodePrimaryKeyMapping, _ = queries.BindMapping(prefectureCodeType, prefectureCodeMapping, prefectureCodePrimaryKeyColumns)
	prefectureCodeInsertCacheMut       sync.RWMutex
	prefectureCodeInsertCache          = make(map[string]insertCache)
	prefectureCodeUpdateCacheMut       sync.RWMutex
	prefectureCodeUpdateCache          = make(map[string]updateCache)
	prefectureCodeUpsertCacheMut       sync.RWMutex
	prefectureCodeUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var prefectureCodeAfterSelectHooks []PrefectureCodeHook

var prefectureCodeBeforeInsertHooks []PrefectureCodeHook
var prefectureCodeAfterInsertHooks []PrefectureCodeHook

var prefectureCodeBeforeUpdateHooks []PrefectureCodeHook
var prefectureCodeAfterUpdateHooks []PrefectureCodeHook

var prefectureCodeBeforeDeleteHooks []PrefectureCodeHook
var prefectureCodeAfterDeleteHooks []PrefectureCodeHook

var prefectureCodeBeforeUpsertHooks []PrefectureCodeHook
var prefectureCodeAfterUpsertHooks []PrefectureCodeHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *PrefectureCode) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range prefectureCodeAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *PrefectureCode) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range prefectureCodeBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *PrefectureCode) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range prefectureCodeAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *PrefectureCode) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range prefectureCodeBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *PrefectureCode) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range prefectureCodeAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *PrefectureCode) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range prefectureCodeBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *PrefectureCode) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range prefectureCodeAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *PrefectureCode) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range prefectureCodeBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *PrefectureCode) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range prefectureCodeAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPrefectureCodeHook registers your hook function for all future operations.
func AddPrefectureCodeHook(hookPoint boil.HookPoint, prefectureCodeHook PrefectureCodeHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		prefectureCodeAfterSelectHooks = append(prefectureCodeAfterSelectHooks, prefectureCodeHook)
	case boil.BeforeInsertHook:
		prefectureCodeBeforeInsertHooks = append(prefectureCodeBeforeInsertHooks, prefectureCodeHook)
	case boil.AfterInsertHook:
		prefectureCodeAfterInsertHooks = append(prefectureCodeAfterInsertHooks, prefectureCodeHook)
	case boil.BeforeUpdateHook:
		prefectureCodeBeforeUpdateHooks = append(prefectureCodeBeforeUpdateHooks, prefectureCodeHook)
	case boil.AfterUpdateHook:
		prefectureCodeAfterUpdateHooks = append(prefectureCodeAfterUpdateHooks, prefectureCodeHook)
	case boil.BeforeDeleteHook:
		prefectureCodeBeforeDeleteHooks = append(prefectureCodeBeforeDeleteHooks, prefectureCodeHook)
	case boil.AfterDeleteHook:
		prefectureCodeAfterDeleteHooks = append(prefectureCodeAfterDeleteHooks, prefectureCodeHook)
	case boil.BeforeUpsertHook:
		prefectureCodeBeforeUpsertHooks = append(prefectureCodeBeforeUpsertHooks, prefectureCodeHook)
	case boil.AfterUpsertHook:
		prefectureCodeAfterUpsertHooks = append(prefectureCodeAfterUpsertHooks, prefectureCodeHook)
	}
}

// One returns a single prefectureCode record from the query.
func (q prefectureCodeQuery) One(ctx context.Context, exec boil.ContextExecutor) (*PrefectureCode, error) {
	o := &PrefectureCode{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for PrefectureCodes")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all PrefectureCode records from the query.
func (q prefectureCodeQuery) All(ctx context.Context, exec boil.ContextExecutor) (PrefectureCodeSlice, error) {
	var o []*PrefectureCode

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to PrefectureCode slice")
	}

	if len(prefectureCodeAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all PrefectureCode records in the query.
func (q prefectureCodeQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count PrefectureCodes rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q prefectureCodeQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if PrefectureCodes exists")
	}

	return count > 0, nil
}

// PrefectureCodes retrieves all the records using an executor.
func PrefectureCodes(mods ...qm.QueryMod) prefectureCodeQuery {
	mods = append(mods, qm.From("`PrefectureCodes`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`PrefectureCodes`.*"})
	}

	return prefectureCodeQuery{q}
}

// FindPrefectureCode retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPrefectureCode(ctx context.Context, exec boil.ContextExecutor, iD uint, selectCols ...string) (*PrefectureCode, error) {
	prefectureCodeObj := &PrefectureCode{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `PrefectureCodes` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, prefectureCodeObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from PrefectureCodes")
	}

	if err = prefectureCodeObj.doAfterSelectHooks(ctx, exec); err != nil {
		return prefectureCodeObj, err
	}

	return prefectureCodeObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *PrefectureCode) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no PrefectureCodes provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(prefectureCodeColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	prefectureCodeInsertCacheMut.RLock()
	cache, cached := prefectureCodeInsertCache[key]
	prefectureCodeInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			prefectureCodeAllColumns,
			prefectureCodeColumnsWithDefault,
			prefectureCodeColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(prefectureCodeType, prefectureCodeMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(prefectureCodeType, prefectureCodeMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `PrefectureCodes` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `PrefectureCodes` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `PrefectureCodes` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, prefectureCodePrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into PrefectureCodes")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for PrefectureCodes")
	}

CacheNoHooks:
	if !cached {
		prefectureCodeInsertCacheMut.Lock()
		prefectureCodeInsertCache[key] = cache
		prefectureCodeInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the PrefectureCode.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *PrefectureCode) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	prefectureCodeUpdateCacheMut.RLock()
	cache, cached := prefectureCodeUpdateCache[key]
	prefectureCodeUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			prefectureCodeAllColumns,
			prefectureCodePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update PrefectureCodes, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `PrefectureCodes` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, prefectureCodePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(prefectureCodeType, prefectureCodeMapping, append(wl, prefectureCodePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update PrefectureCodes row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for PrefectureCodes")
	}

	if !cached {
		prefectureCodeUpdateCacheMut.Lock()
		prefectureCodeUpdateCache[key] = cache
		prefectureCodeUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q prefectureCodeQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for PrefectureCodes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for PrefectureCodes")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PrefectureCodeSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), prefectureCodePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `PrefectureCodes` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, prefectureCodePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in prefectureCode slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all prefectureCode")
	}
	return rowsAff, nil
}

var mySQLPrefectureCodeUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *PrefectureCode) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no PrefectureCodes provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(prefectureCodeColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLPrefectureCodeUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	prefectureCodeUpsertCacheMut.RLock()
	cache, cached := prefectureCodeUpsertCache[key]
	prefectureCodeUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			prefectureCodeAllColumns,
			prefectureCodeColumnsWithDefault,
			prefectureCodeColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			prefectureCodeAllColumns,
			prefectureCodePrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert PrefectureCodes, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`PrefectureCodes`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `PrefectureCodes` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(prefectureCodeType, prefectureCodeMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(prefectureCodeType, prefectureCodeMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for PrefectureCodes")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(prefectureCodeType, prefectureCodeMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for PrefectureCodes")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for PrefectureCodes")
	}

CacheNoHooks:
	if !cached {
		prefectureCodeUpsertCacheMut.Lock()
		prefectureCodeUpsertCache[key] = cache
		prefectureCodeUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single PrefectureCode record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *PrefectureCode) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no PrefectureCode provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), prefectureCodePrimaryKeyMapping)
	sql := "DELETE FROM `PrefectureCodes` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from PrefectureCodes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for PrefectureCodes")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q prefectureCodeQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no prefectureCodeQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from PrefectureCodes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for PrefectureCodes")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PrefectureCodeSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(prefectureCodeBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), prefectureCodePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `PrefectureCodes` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, prefectureCodePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from prefectureCode slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for PrefectureCodes")
	}

	if len(prefectureCodeAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *PrefectureCode) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPrefectureCode(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PrefectureCodeSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PrefectureCodeSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), prefectureCodePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `PrefectureCodes`.* FROM `PrefectureCodes` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, prefectureCodePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in PrefectureCodeSlice")
	}

	*o = slice

	return nil
}

// PrefectureCodeExists checks if the PrefectureCode row exists.
func PrefectureCodeExists(ctx context.Context, exec boil.ContextExecutor, iD uint) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `PrefectureCodes` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if PrefectureCodes exists")
	}

	return exists, nil
}

// Exists checks if the PrefectureCode row exists.
func (o *PrefectureCode) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return PrefectureCodeExists(ctx, exec, o.ID)
}
