// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Prefecture is an object representing the database table.
type Prefecture struct {
	ID      uint      `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name    string    `boil:"name" json:"name" toml:"name" yaml:"name"`
	Created time.Time `boil:"created" json:"created" toml:"created" yaml:"created"`
	Updated time.Time `boil:"updated" json:"updated" toml:"updated" yaml:"updated"`

	R *prefectureR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L prefectureL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PrefectureColumns = struct {
	ID      string
	Name    string
	Created string
	Updated string
}{
	ID:      "id",
	Name:    "name",
	Created: "created",
	Updated: "updated",
}

var PrefectureTableColumns = struct {
	ID      string
	Name    string
	Created string
	Updated string
}{
	ID:      "Prefectures.id",
	Name:    "Prefectures.name",
	Created: "Prefectures.created",
	Updated: "Prefectures.updated",
}

// Generated where

var PrefectureWhere = struct {
	ID      whereHelperuint
	Name    whereHelperstring
	Created whereHelpertime_Time
	Updated whereHelpertime_Time
}{
	ID:      whereHelperuint{field: "`Prefectures`.`id`"},
	Name:    whereHelperstring{field: "`Prefectures`.`name`"},
	Created: whereHelpertime_Time{field: "`Prefectures`.`created`"},
	Updated: whereHelpertime_Time{field: "`Prefectures`.`updated`"},
}

// PrefectureRels is where relationship names are stored.
var PrefectureRels = struct {
}{}

// prefectureR is where relationships are stored.
type prefectureR struct {
}

// NewStruct creates a new relationship struct
func (*prefectureR) NewStruct() *prefectureR {
	return &prefectureR{}
}

// prefectureL is where Load methods for each relationship are stored.
type prefectureL struct{}

var (
	prefectureAllColumns            = []string{"id", "name", "created", "updated"}
	prefectureColumnsWithoutDefault = []string{"id", "name"}
	prefectureColumnsWithDefault    = []string{"created", "updated"}
	prefecturePrimaryKeyColumns     = []string{"id"}
	prefectureGeneratedColumns      = []string{}
)

type (
	// PrefectureSlice is an alias for a slice of pointers to Prefecture.
	// This should almost always be used instead of []Prefecture.
	PrefectureSlice []*Prefecture
	// PrefectureHook is the signature for custom Prefecture hook methods
	PrefectureHook func(context.Context, boil.ContextExecutor, *Prefecture) error

	prefectureQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	prefectureType                 = reflect.TypeOf(&Prefecture{})
	prefectureMapping              = queries.MakeStructMapping(prefectureType)
	prefecturePrimaryKeyMapping, _ = queries.BindMapping(prefectureType, prefectureMapping, prefecturePrimaryKeyColumns)
	prefectureInsertCacheMut       sync.RWMutex
	prefectureInsertCache          = make(map[string]insertCache)
	prefectureUpdateCacheMut       sync.RWMutex
	prefectureUpdateCache          = make(map[string]updateCache)
	prefectureUpsertCacheMut       sync.RWMutex
	prefectureUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var prefectureAfterSelectHooks []PrefectureHook

var prefectureBeforeInsertHooks []PrefectureHook
var prefectureAfterInsertHooks []PrefectureHook

var prefectureBeforeUpdateHooks []PrefectureHook
var prefectureAfterUpdateHooks []PrefectureHook

var prefectureBeforeDeleteHooks []PrefectureHook
var prefectureAfterDeleteHooks []PrefectureHook

var prefectureBeforeUpsertHooks []PrefectureHook
var prefectureAfterUpsertHooks []PrefectureHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Prefecture) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range prefectureAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Prefecture) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range prefectureBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Prefecture) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range prefectureAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Prefecture) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range prefectureBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Prefecture) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range prefectureAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Prefecture) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range prefectureBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Prefecture) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range prefectureAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Prefecture) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range prefectureBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Prefecture) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range prefectureAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPrefectureHook registers your hook function for all future operations.
func AddPrefectureHook(hookPoint boil.HookPoint, prefectureHook PrefectureHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		prefectureAfterSelectHooks = append(prefectureAfterSelectHooks, prefectureHook)
	case boil.BeforeInsertHook:
		prefectureBeforeInsertHooks = append(prefectureBeforeInsertHooks, prefectureHook)
	case boil.AfterInsertHook:
		prefectureAfterInsertHooks = append(prefectureAfterInsertHooks, prefectureHook)
	case boil.BeforeUpdateHook:
		prefectureBeforeUpdateHooks = append(prefectureBeforeUpdateHooks, prefectureHook)
	case boil.AfterUpdateHook:
		prefectureAfterUpdateHooks = append(prefectureAfterUpdateHooks, prefectureHook)
	case boil.BeforeDeleteHook:
		prefectureBeforeDeleteHooks = append(prefectureBeforeDeleteHooks, prefectureHook)
	case boil.AfterDeleteHook:
		prefectureAfterDeleteHooks = append(prefectureAfterDeleteHooks, prefectureHook)
	case boil.BeforeUpsertHook:
		prefectureBeforeUpsertHooks = append(prefectureBeforeUpsertHooks, prefectureHook)
	case boil.AfterUpsertHook:
		prefectureAfterUpsertHooks = append(prefectureAfterUpsertHooks, prefectureHook)
	}
}

// One returns a single prefecture record from the query.
func (q prefectureQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Prefecture, error) {
	o := &Prefecture{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for Prefectures")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Prefecture records from the query.
func (q prefectureQuery) All(ctx context.Context, exec boil.ContextExecutor) (PrefectureSlice, error) {
	var o []*Prefecture

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Prefecture slice")
	}

	if len(prefectureAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Prefecture records in the query.
func (q prefectureQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count Prefectures rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q prefectureQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if Prefectures exists")
	}

	return count > 0, nil
}

// Prefectures retrieves all the records using an executor.
func Prefectures(mods ...qm.QueryMod) prefectureQuery {
	mods = append(mods, qm.From("`Prefectures`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`Prefectures`.*"})
	}

	return prefectureQuery{q}
}

// FindPrefecture retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPrefecture(ctx context.Context, exec boil.ContextExecutor, iD uint, selectCols ...string) (*Prefecture, error) {
	prefectureObj := &Prefecture{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `Prefectures` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, prefectureObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from Prefectures")
	}

	if err = prefectureObj.doAfterSelectHooks(ctx, exec); err != nil {
		return prefectureObj, err
	}

	return prefectureObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Prefecture) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no Prefectures provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(prefectureColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	prefectureInsertCacheMut.RLock()
	cache, cached := prefectureInsertCache[key]
	prefectureInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			prefectureAllColumns,
			prefectureColumnsWithDefault,
			prefectureColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(prefectureType, prefectureMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(prefectureType, prefectureMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `Prefectures` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `Prefectures` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `Prefectures` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, prefecturePrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into Prefectures")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for Prefectures")
	}

CacheNoHooks:
	if !cached {
		prefectureInsertCacheMut.Lock()
		prefectureInsertCache[key] = cache
		prefectureInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Prefecture.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Prefecture) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	prefectureUpdateCacheMut.RLock()
	cache, cached := prefectureUpdateCache[key]
	prefectureUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			prefectureAllColumns,
			prefecturePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update Prefectures, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `Prefectures` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, prefecturePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(prefectureType, prefectureMapping, append(wl, prefecturePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update Prefectures row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for Prefectures")
	}

	if !cached {
		prefectureUpdateCacheMut.Lock()
		prefectureUpdateCache[key] = cache
		prefectureUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q prefectureQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for Prefectures")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for Prefectures")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PrefectureSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), prefecturePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `Prefectures` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, prefecturePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in prefecture slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all prefecture")
	}
	return rowsAff, nil
}

var mySQLPrefectureUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Prefecture) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no Prefectures provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(prefectureColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLPrefectureUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	prefectureUpsertCacheMut.RLock()
	cache, cached := prefectureUpsertCache[key]
	prefectureUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			prefectureAllColumns,
			prefectureColumnsWithDefault,
			prefectureColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			prefectureAllColumns,
			prefecturePrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert Prefectures, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`Prefectures`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `Prefectures` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(prefectureType, prefectureMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(prefectureType, prefectureMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for Prefectures")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(prefectureType, prefectureMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for Prefectures")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for Prefectures")
	}

CacheNoHooks:
	if !cached {
		prefectureUpsertCacheMut.Lock()
		prefectureUpsertCache[key] = cache
		prefectureUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Prefecture record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Prefecture) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Prefecture provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), prefecturePrimaryKeyMapping)
	sql := "DELETE FROM `Prefectures` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from Prefectures")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for Prefectures")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q prefectureQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no prefectureQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from Prefectures")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for Prefectures")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PrefectureSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(prefectureBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), prefecturePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `Prefectures` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, prefecturePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from prefecture slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for Prefectures")
	}

	if len(prefectureAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Prefecture) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPrefecture(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PrefectureSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PrefectureSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), prefecturePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `Prefectures`.* FROM `Prefectures` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, prefecturePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in PrefectureSlice")
	}

	*o = slice

	return nil
}

// PrefectureExists checks if the Prefecture row exists.
func PrefectureExists(ctx context.Context, exec boil.ContextExecutor, iD uint) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `Prefectures` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if Prefectures exists")
	}

	return exists, nil
}

// Exists checks if the Prefecture row exists.
func (o *Prefecture) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return PrefectureExists(ctx, exec, o.ID)
}
