// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testTsunamiConnects(t *testing.T) {
	t.Parallel()

	query := TsunamiConnects()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testTsunamiConnectsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TsunamiConnect{}
	if err = randomize.Struct(seed, o, tsunamiConnectDBTypes, true, tsunamiConnectColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TsunamiConnect struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := TsunamiConnects().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTsunamiConnectsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TsunamiConnect{}
	if err = randomize.Struct(seed, o, tsunamiConnectDBTypes, true, tsunamiConnectColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TsunamiConnect struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := TsunamiConnects().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := TsunamiConnects().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTsunamiConnectsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TsunamiConnect{}
	if err = randomize.Struct(seed, o, tsunamiConnectDBTypes, true, tsunamiConnectColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TsunamiConnect struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := TsunamiConnectSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := TsunamiConnects().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTsunamiConnectsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TsunamiConnect{}
	if err = randomize.Struct(seed, o, tsunamiConnectDBTypes, true, tsunamiConnectColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TsunamiConnect struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := TsunamiConnectExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if TsunamiConnect exists: %s", err)
	}
	if !e {
		t.Errorf("Expected TsunamiConnectExists to return true, but got false.")
	}
}

func testTsunamiConnectsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TsunamiConnect{}
	if err = randomize.Struct(seed, o, tsunamiConnectDBTypes, true, tsunamiConnectColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TsunamiConnect struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	tsunamiConnectFound, err := FindTsunamiConnect(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if tsunamiConnectFound == nil {
		t.Error("want a record, got nil")
	}
}

func testTsunamiConnectsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TsunamiConnect{}
	if err = randomize.Struct(seed, o, tsunamiConnectDBTypes, true, tsunamiConnectColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TsunamiConnect struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = TsunamiConnects().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testTsunamiConnectsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TsunamiConnect{}
	if err = randomize.Struct(seed, o, tsunamiConnectDBTypes, true, tsunamiConnectColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TsunamiConnect struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := TsunamiConnects().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testTsunamiConnectsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	tsunamiConnectOne := &TsunamiConnect{}
	tsunamiConnectTwo := &TsunamiConnect{}
	if err = randomize.Struct(seed, tsunamiConnectOne, tsunamiConnectDBTypes, false, tsunamiConnectColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TsunamiConnect struct: %s", err)
	}
	if err = randomize.Struct(seed, tsunamiConnectTwo, tsunamiConnectDBTypes, false, tsunamiConnectColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TsunamiConnect struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = tsunamiConnectOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = tsunamiConnectTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := TsunamiConnects().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testTsunamiConnectsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	tsunamiConnectOne := &TsunamiConnect{}
	tsunamiConnectTwo := &TsunamiConnect{}
	if err = randomize.Struct(seed, tsunamiConnectOne, tsunamiConnectDBTypes, false, tsunamiConnectColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TsunamiConnect struct: %s", err)
	}
	if err = randomize.Struct(seed, tsunamiConnectTwo, tsunamiConnectDBTypes, false, tsunamiConnectColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TsunamiConnect struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = tsunamiConnectOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = tsunamiConnectTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TsunamiConnects().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func tsunamiConnectBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *TsunamiConnect) error {
	*o = TsunamiConnect{}
	return nil
}

func tsunamiConnectAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *TsunamiConnect) error {
	*o = TsunamiConnect{}
	return nil
}

func tsunamiConnectAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *TsunamiConnect) error {
	*o = TsunamiConnect{}
	return nil
}

func tsunamiConnectBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *TsunamiConnect) error {
	*o = TsunamiConnect{}
	return nil
}

func tsunamiConnectAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *TsunamiConnect) error {
	*o = TsunamiConnect{}
	return nil
}

func tsunamiConnectBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *TsunamiConnect) error {
	*o = TsunamiConnect{}
	return nil
}

func tsunamiConnectAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *TsunamiConnect) error {
	*o = TsunamiConnect{}
	return nil
}

func tsunamiConnectBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *TsunamiConnect) error {
	*o = TsunamiConnect{}
	return nil
}

func tsunamiConnectAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *TsunamiConnect) error {
	*o = TsunamiConnect{}
	return nil
}

func testTsunamiConnectsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &TsunamiConnect{}
	o := &TsunamiConnect{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, tsunamiConnectDBTypes, false); err != nil {
		t.Errorf("Unable to randomize TsunamiConnect object: %s", err)
	}

	AddTsunamiConnectHook(boil.BeforeInsertHook, tsunamiConnectBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	tsunamiConnectBeforeInsertHooks = []TsunamiConnectHook{}

	AddTsunamiConnectHook(boil.AfterInsertHook, tsunamiConnectAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	tsunamiConnectAfterInsertHooks = []TsunamiConnectHook{}

	AddTsunamiConnectHook(boil.AfterSelectHook, tsunamiConnectAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	tsunamiConnectAfterSelectHooks = []TsunamiConnectHook{}

	AddTsunamiConnectHook(boil.BeforeUpdateHook, tsunamiConnectBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	tsunamiConnectBeforeUpdateHooks = []TsunamiConnectHook{}

	AddTsunamiConnectHook(boil.AfterUpdateHook, tsunamiConnectAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	tsunamiConnectAfterUpdateHooks = []TsunamiConnectHook{}

	AddTsunamiConnectHook(boil.BeforeDeleteHook, tsunamiConnectBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	tsunamiConnectBeforeDeleteHooks = []TsunamiConnectHook{}

	AddTsunamiConnectHook(boil.AfterDeleteHook, tsunamiConnectAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	tsunamiConnectAfterDeleteHooks = []TsunamiConnectHook{}

	AddTsunamiConnectHook(boil.BeforeUpsertHook, tsunamiConnectBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	tsunamiConnectBeforeUpsertHooks = []TsunamiConnectHook{}

	AddTsunamiConnectHook(boil.AfterUpsertHook, tsunamiConnectAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	tsunamiConnectAfterUpsertHooks = []TsunamiConnectHook{}
}

func testTsunamiConnectsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TsunamiConnect{}
	if err = randomize.Struct(seed, o, tsunamiConnectDBTypes, true, tsunamiConnectColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TsunamiConnect struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TsunamiConnects().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testTsunamiConnectsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TsunamiConnect{}
	if err = randomize.Struct(seed, o, tsunamiConnectDBTypes, true); err != nil {
		t.Errorf("Unable to randomize TsunamiConnect struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(tsunamiConnectColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := TsunamiConnects().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testTsunamiConnectsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TsunamiConnect{}
	if err = randomize.Struct(seed, o, tsunamiConnectDBTypes, true, tsunamiConnectColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TsunamiConnect struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testTsunamiConnectsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TsunamiConnect{}
	if err = randomize.Struct(seed, o, tsunamiConnectDBTypes, true, tsunamiConnectColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TsunamiConnect struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := TsunamiConnectSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testTsunamiConnectsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TsunamiConnect{}
	if err = randomize.Struct(seed, o, tsunamiConnectDBTypes, true, tsunamiConnectColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TsunamiConnect struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := TsunamiConnects().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	tsunamiConnectDBTypes = map[string]string{`ID`: `int`, `TsunamiID`: `int`, `EventID`: `int`, `Created`: `datetime`}
	_                     = bytes.MinRead
)

func testTsunamiConnectsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(tsunamiConnectPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(tsunamiConnectAllColumns) == len(tsunamiConnectPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &TsunamiConnect{}
	if err = randomize.Struct(seed, o, tsunamiConnectDBTypes, true, tsunamiConnectColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TsunamiConnect struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TsunamiConnects().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, tsunamiConnectDBTypes, true, tsunamiConnectPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize TsunamiConnect struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testTsunamiConnectsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(tsunamiConnectAllColumns) == len(tsunamiConnectPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &TsunamiConnect{}
	if err = randomize.Struct(seed, o, tsunamiConnectDBTypes, true, tsunamiConnectColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TsunamiConnect struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TsunamiConnects().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, tsunamiConnectDBTypes, true, tsunamiConnectPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize TsunamiConnect struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(tsunamiConnectAllColumns, tsunamiConnectPrimaryKeyColumns) {
		fields = tsunamiConnectAllColumns
	} else {
		fields = strmangle.SetComplement(
			tsunamiConnectAllColumns,
			tsunamiConnectPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := TsunamiConnectSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testTsunamiConnectsUpsert(t *testing.T) {
	t.Parallel()

	if len(tsunamiConnectAllColumns) == len(tsunamiConnectPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLTsunamiConnectUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := TsunamiConnect{}
	if err = randomize.Struct(seed, &o, tsunamiConnectDBTypes, false); err != nil {
		t.Errorf("Unable to randomize TsunamiConnect struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert TsunamiConnect: %s", err)
	}

	count, err := TsunamiConnects().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, tsunamiConnectDBTypes, false, tsunamiConnectPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize TsunamiConnect struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert TsunamiConnect: %s", err)
	}

	count, err = TsunamiConnects().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
